apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: nginx
    environment: production
  name: middleware-service
  namespace: {{ .Release.Namespace }}

spec:
  #host: middleware-service-app1.apps-crc.testing
  port:
    targetPort: 80
  to:
    kind: Service
    name: middleware-service
    weight: 100
  wildcardPolicy: None