apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    environment: production
  name: middleware-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
    environment: production
  type: NodePort